[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "frontend"
  publish = "dist/gabbar-singh-truck/browser"
  command = "npm install && npm run build:prod"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
